In [1]:
import json
import pandas as pd
from pathlib import Path
from sina.config.paths import GAS_DATA

In [2]:
CSV_PATH = GAS_DATA / Path("municipios.csv")
df_municipios = pd.read_csv(CSV_PATH)

In [3]:
df_municipios.rename(columns={
    "_id": "ClaveEntidad",
    "Estado": "EntidadFederativa",
    "CodMunicipio": "ClaveMunicipio",
    "MUNICIPIO": "Municipio",
}, inplace=True)

In [4]:
df_municipios

      ClaveEntidad EntidadFederativa  ClaveMunicipio              Municipio
0                1    AGUASCALIENTES               1         AGUASCALIENTES
1                2    AGUASCALIENTES               2               ASIENTOS
2                3    AGUASCALIENTES               3               CALVILLO
3                4    AGUASCALIENTES               4                  COSÍO
4                5    AGUASCALIENTES               5            JESÚS MARÍA
...            ...               ...             ...                    ...
2473          2474         ZACATECAS              54          VILLA HIDALGO
2474          2475         ZACATECAS              55             VILLANUEVA
2475          2476         ZACATECAS              56              ZACATECAS
2476          2477         ZACATECAS              57               TRANCOSO
2477          2478         ZACATECAS              58  SANTA MARÍA DE LA PAZ

[2478 rows x 4 columns]

In [5]:
df_municipios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2478 entries, 0 to 2477
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ClaveEntidad       2478 non-null   int64
 1   EntidadFederativa  2478 non-null   object
 2   ClaveMunicipio     2478 non-null   int64
 3   Municipio          2478 non-null   object
dtypes: int64(2), object(2)
memory usage: 77.6+ KB

In [6]:
from unidecode import unidecode
def limpiar_texto(texto: str) -> str:
    if not isinstance(texto, str):
        return texto
    return unidecode(texto).lower().strip()

df_municipios["EntidadFederativa"] = df_municipios["EntidadFederativa"].apply(limpiar_texto)
df_municipios["Municipio"]         = df_municipios["Municipio"].apply(limpiar_texto)

# ✅ Verificar que funcionó
print(df_municipios["EntidadFederativa"].unique())
print(df_municipios["Municipio"].head(10))

['aguascalientes' 'baja california' 'baja california sur' 'campeche'
 'coahuila de zaragoza' 'colima' 'chiapas' 'chihuahua' 'ciudad de mexico'
 'durango' 'guanajuato' 'guerrero' 'hidalgo' 'jalisco' 'mexico'
 'michoacan de ocampo' 'morelos' 'nayarit' 'nuevo leon' 'oaxaca' 'puebla'
 'queretaro' 'quintana roo' 'san luis potosi' 'sinaloa' 'sonora' 'tabasco'
 'tamaulipas' 'tlaxcala' 'veracruz de ignacio de la llave' 'yucatan'
 'zacatecas']
0         aguascalientes
1               asientos
2               calvillo
3                  cosio
4            jesus maria
5    pabellon de arteaga
6        rincon de romos
7     san jose de gracia
8               tepezala
9               el llano
Name: Municipio, dtype: object

In [7]:
entidades_unicas = df_municipios["EntidadFederativa"].unique()
print(f"Entidades únicas: {len(entidades_unicas)}")
print(entidades_unicas)

Entidades únicas: 32
['aguascalientes' 'baja california' 'baja california sur' 'campeche'
 'coahuila de zaragoza' 'colima' 'chiapas' 'chihuahua' 'ciudad de mexico'
 'durango' 'guanajuato' 'guerrero' 'hidalgo' 'jalisco' 'mexico'
 'michoacan de ocampo' 'morelos' 'nayarit' 'nuevo leon' 'oaxaca' 'puebla'
 'queretaro' 'quintana roo' 'san luis potosi' 'sinaloa' 'sonora' 'tabasco'
 'tamaulipas' 'tlaxcala' 'veracruz de ignacio de la llave' 'yucatan'
 'zacatecas']

In [8]:
mapa_entidades = {
    entidad: str(i + 1).zfill(2)
    for i, entidad in enumerate(entidades_unicas)
}

In [9]:
for k, v in mapa_entidades.items():
    print(f"  {v} → {k}")

df_municipios["ClaveEntidad"] = (
    df_municipios["EntidadFederativa"]
    .map(mapa_entidades)
)
print(df_municipios[["ClaveEntidad", "EntidadFederativa"]].drop_duplicates().head(10))
print(f"\nShape: {df_municipios.shape}")
df_municipios.head(10)

  01 → aguascalientes
  02 → baja california
  03 → baja california sur
  04 → campeche
  05 → coahuila de zaragoza
  06 → colima
  07 → chiapas
  08 → chihuahua
  09 → ciudad de mexico
  10 → durango
  11 → guanajuato
  12 → guerrero
  13 → hidalgo
  14 → jalisco
  15 → mexico
  16 → michoacan de ocampo
  17 → morelos
  18 → nayarit
  19 → nuevo leon
  20 → oaxaca
  21 → puebla
  22 → queretaro
  23 → quintana roo
  24 → san luis potosi
  25 → sinaloa
  26 → sonora
  27 → tabasco
  28 → tamaulipas
  29 → tlaxcala
  30 → veracruz de ignacio de la llave
  31 → yucatan
  32 → zacatecas
    ClaveEntidad     EntidadFederativa
0             01        aguascalientes
11            02       baja california
18            03   baja california sur
23            04              campeche
36            05  coahuila de zaragoza
74            06                colima
84            07               chiapas
208           08             chihuahua
275           09      ciudad de mexico
291           10               durango

Shape: (2478, 4)

  ClaveEntidad EntidadFederativa  ClaveMunicipio            Municipio
0           01    aguascalientes               1       aguascalientes
1           01    aguascalientes               2             asientos
2           01    aguascalientes               3             calvillo
3           01    aguascalientes               4                cosio
4           01    aguascalientes               5          jesus maria
5           01    aguascalientes               6  pabellon de arteaga
6           01    aguascalientes               7      rincon de romos
7           01    aguascalientes               8   san jose de gracia
8           01    aguascalientes               9             tepezala
9           01    aguascalientes              10             el llano

In [11]:
df_municipios["ClaveMunicipio"] = (
    df_municipios["ClaveMunicipio"]
    .astype(str)
    .str.zfill(3)   
)

# Verificar
print(df_municipios[["ClaveEntidad", "ClaveMunicipio"]].head(10))
print(df_municipios[df_municipios["ClaveEntidad"] == "26"].head(5))

  ClaveEntidad ClaveMunicipio
0           01            001
1           01            002
2           01            003
3           01            004
4           01            005
5           01            006
6           01            007
7           01            008
8           01            009
9           01            010
     ClaveEntidad EntidadFederativa ClaveMunicipio    Municipio
1910           26            sonora            001      aconchi
1911           26            sonora            002  agua prieta
1912           26            sonora            003       alamos
1913           26            sonora            004        altar
1914           26            sonora            005     arivechi

In [12]:
catalogo = {}

for _, row in df_municipios.iterrows():
    entidad_id = row["ClaveEntidad"]
    entidad_name = row["EntidadFederativa"]
    mun_id = row["ClaveMunicipio"]
    mun_name = row["Municipio"]

    if entidad_name not in catalogo:
        catalogo[entidad_name] = {
            "id"    : entidad_id,
            "municipios": {}
        }

    catalogo[entidad_name]['municipios'][mun_name] = {
        "id"    : mun_id
    }

In [13]:
catalogo

{'aguascalientes': {'id': '01',
  'municipios': {'aguascalientes': {'id': '001'},
   'asientos': {'id': '002'},
   'calvillo': {'id': '003'},
   'cosio': {'id': '004'},
   'jesus maria': {'id': '005'},
   'pabellon de arteaga': {'id': '006'},
   'rincon de romos': {'id': '007'},
   'san jose de gracia': {'id': '008'},
   'tepezala': {'id': '009'},
   'el llano': {'id': '010'},
   'san francisco de los romo': {'id': '011'}}},
 'baja california': {'id': '02',
  'municipios': {'ensenada': {'id': '001'},
   'mexicali': {'id': '002'},
   'tecate': {'id': '003'},
   'tijuana': {'id': '004'},
   'playas de rosarito': {'id': '005'},
   'san quintin': {'id': '006'},
   'san felipe': {'id': '007'}}},
 'baja california sur': {'id': '03',
  'municipios': {'comondu': {'id': '001'},
   'mulege': {'id': '002'},
   'la paz': {'id': '003'},
   'los cabos': {'id': '008'},
   'loreto': {'id': '009'}}},
 'campeche': {'id': '04',
  'municipios': {'calkini': {'id': '001'},
   'campeche': {'id': '002'},
   'carmen': {'id': '003'},
   'champoton': {'id': '004'},
   'hecelchakan': {'id': '005'},
   'hopelchen': {'id': '006'},
   'palizada': {'id': '007'},
   'tenabo': {'id': '008'},
   'escarcega': {'id': '009'},
   'calakmul': {'id': '010'},
   'candelaria': {'id': '011'},
   'seybaplaya': {'id': '012'},
   'dzitbalche': {'id': '013'}}},
 'coahuila de zaragoza': {'id': '05',
  'municipios': {'abasolo': {'id': '001'},
   'acuna': {'id': '002'},
   'allende': {'id': '003'},
   'arteaga': {'id': '004'},
   'candela': {'id': '005'},
   'castanos': {'id': '006'},
   'cuatro cienegas': {'id': '007'},
   'escobedo': {'id': '008'},
   'francisco i. madero': {'id': '009'},
   'frontera': {'id': '010'},
   'general cepeda': {'id': '011'},
   'guerrero': {'id': '012'},
   'hidalgo': {'id': '013'},
   'jimenez': {'id': '014'},
   'juarez': {'id': '015'},
   'lamadrid': {'id': '016'},
   'matamoros': {'id': '017'},
   'monclova': {'id': '018'},
   'morelos': {'id': '019'},
   'muzquiz': {'id': '020'},
   'nadadores': {'id': '021'},
   'nava': {'id': '022'},
   'ocampo': {'id': '023'},
   'parras': {'id': '024'},
   'piedras negras': {'id': '025'},
   'progreso': {'id': '026'},
   'ramos arizpe': {'id': '027'},
   'sabinas': {'id': '028'},
   'sacramento': {'id': '029'},
   'saltillo': {'id': '030'},
   'san buenaventura': {'id': '031'},
   'san juan de sabinas': {'id': '032'},
   'san pedro': {'id': '033'},
   'sierra mojada': {'id': '034'},
   'torreon': {'id': '035'},
   'viesca': {'id': '036'},
   'villa union': {'id': '037'},
   'zaragoza': {'id': '038'}}},
 'colima': {'id': '06',
  'municipios': {'armeria': {'id': '001'},
   'colima': {'id': '002'},
   'comala': {'id': '003'},
   'coquimatlan': {'id': '004'},
   'cuauhtemoc': {'id': '005'},
   'ixtlahuacan': {'id': '006'},
   'manzanillo': {'id': '007'},
   'minatitlan': {'id': '008'},
   'tecoman': {'id': '009'},
   'villa de alvarez': {'id': '010'}}},
 'chiapas': {'id': '07',
  'municipios': {'acacoyagua': {'id': '001'},
   'acala': {'id': '002'},
   'acapetahua': {'id': '003'},
   'altamirano': {'id': '004'},
   'amatan': {'id': '005'},
   'amatenango de la frontera': {'id': '006'},
   'amatenango del valle': {'id': '007'},
   'angel albino corzo': {'id': '008'},
   'arriaga': {'id': '009'},
   'bejucal de ocampo': {'id': '010'},
   'bella vista': {'id': '011'},
   'berriozabal': {'id': '012'},
   'bochil': {'id': '013'},
   'el bosque': {'id': '014'},
   'cacahoatan': {'id': '015'},
   'catazaja': {'id': '016'},
   'cintalapa de figueroa': {'id': '017'},
   'coapilla': {'id': '018'},
   'comitan de dominguez': {'id': '019'},
   'la concordia': {'id': '020'},
   'copainala': {'id': '021'},
   'chalchihuitan': {'id': '022'},
   'chamula': {'id': '023'},
   'chanal': {'id': '024'},
   'chapultenango': {'id': '025'},
   'chenalho': {'id': '026'},
   'chiapa de corzo': {'id': '027'},
   'chiapilla': {'id': '028'},
   'chicoasen': {'id': '029'},
   'chicomuselo': {'id': '030'},
   'chilon': {'id': '031'},
   'escuintla': {'id': '032'},
   'francisco leon': {'id': '033'},
   'frontera comalapa': {'id': '034'},
   'frontera hidalgo': {'id': '035'},
   'la grandeza': {'id': '036'},
   'huehuetan': {'id': '037'},
   'huixtan': {'id': '038'},
   'huitiupan': {'id': '039'},
   'huixtla': {'id': '040'},
   'la independencia': {'id': '041'},
   'ixhuatan': {'id': '042'},
   'ixtacomitan': {'id': '043'},
   'ixtapa': {'id': '044'},
   'ixtapangajoya': {'id': '045'},
   'jiquipilas': {'id': '046'},
   'jitotol': {'id': '047'},
   'juarez': {'id': '048'},
   'larrainzar': {'id': '049'},
   'la libertad': {'id': '050'},
   'mapastepec': {'id': '051'},
   'las margaritas': {'id': '052'},
   'mazapa de madero': {'id': '053'},
   'mazatan': {'id': '054'},
   'metapa': {'id': '055'},
   'mitontic': {'id': '056'},
   'motozintla': {'id': '057'},
   'nicolas ruiz': {'id': '058'},
   'ocosingo': {'id': '059'},
   'ocotepec': {'id': '060'},
   'ocozocoautla de espinosa': {'id': '061'},
   'ostuacan': {'id': '062'},
   'osumacinta': {'id': '063'},
   'oxchuc': {'id': '064'},
   'palenque': {'id': '065'},
   'pantelho': {'id': '066'},
   'pantepec': {'id': '067'},
   'pichucalco': {'id': '068'},
   'pijijiapan': {'id': '069'},
   'el porvenir': {'id': '070'},
   'villa comaltitlan': {'id': '071'},
   'pueblo nuevo solistahuacan': {'id': '072'},
   'rayon': {'id': '073'},
   'reforma': {'id': '074'},
   'las rosas': {'id': '075'},
   'sabanilla': {'id': '076'},
   'salto de agua': {'id': '077'},
   'san cristobal de las casas': {'id': '078'},
   'san fernando': {'id': '079'},
   'siltepec': {'id': '080'},
   'simojovel': {'id': '081'},
   'sitala': {'id': '082'},
   'socoltenango': {'id': '083'},
   'solosuchiapa': {'id': '084'},
   'soyalo': {'id': '085'},
   'suchiapa': {'id': '086'},
   'suchiate': {'id': '087'},
   'sunuapa': {'id': '088'},
   'tapachula': {'id': '089'},
   'tapalapa': {'id': '090'},
   'tapilula': {'id': '091'},
   'tecpatan': {'id': '092'},
   'tenejapa': {'id': '093'},
   'teopisca': {'id': '094'},
   'tila': {'id': '096'},
   'tonala': {'id': '097'},
   'totolapa': {'id': '098'},
   'la trinitaria': {'id': '099'},
   'tumbala': {'id': '100'},
   'tuxtla gutierrez': {'id': '101'},
   'tuxtla chico': {'id': '102'},
   'tuzantan': {'id': '103'},
   'tzimol': {'id': '104'},
   'union juarez': {'id': '105'},
   'venustiano carranza': {'id': '106'},
   'villa corzo': {'id': '107'},
   'villaflores': {'id': '108'},
   'yajalon': {'id': '109'},
   'san lucas': {'id': '110'},
   'zinacantan': {'id': '111'},
   'san juan cancuc': {'id': '112'},
   'aldama': {'id': '113'},
   'benemerito de las americas': {'id': '114'},
   'maravilla tenejapa': {'id': '115'},
   'marques de comillas': {'id': '116'},
   'montecristo de guerrero': {'id': '117'},
   'san andres duraznal': {'id': '118'},
   'santiago el pinar': {'id': '119'},
   'capitan luis angel vidal': {'id': '120'},
   'rincon chamula san pedro': {'id': '121'},
   'el parral': {'id': '122'},
   'emiliano zapata': {'id': '123'},
   'mezcalapa': {'id': '124'},
   'honduras de la sierra': {'id': '125'}}},
 'chihuahua': {'id': '08',
  'municipios': {'ahumada': {'id': '001'},
   'aldama': {'id': '002'},
   'allende': {'id': '003'},
   'aquiles serdan': {'id': '004'},
   'ascension': {'id': '005'},
   'bachiniva': {'id': '006'},
   'balleza': {'id': '007'},
   'batopilas de manuel gomez morin': {'id': '008'},
   'bocoyna': {'id': '009'},
   'buenaventura': {'id': '010'},
   'camargo': {'id': '011'},
   'carichi': {'id': '012'},
   'casas grandes': {'id': '013'},
   'coronado': {'id': '014'},
   'coyame del sotol': {'id': '015'},
   'la cruz': {'id': '016'},
   'cuauhtemoc': {'id': '017'},
   'cusihuiriachi': {'id': '018'},
   'chihuahua': {'id': '019'},
   'chinipas': {'id': '020'},
   'delicias': {'id': '021'},
   'dr. belisario dominguez': {'id': '022'},
   'galeana': {'id': '023'},
   'santa isabel': {'id': '024'},
   'gomez farias': {'id': '025'},
   'gran morelos': {'id': '026'},
   'guachochi': {'id': '027'},
   'guadalupe': {'id': '028'},
   'guadalupe y calvo': {'id': '029'},
   'guazapares': {'id': '030'},
   'guerrero': {'id': '031'},
   'hidalgo del parral': {'id': '032'},
   'huejotitan': {'id': '033'},
   'ignacio zaragoza': {'id': '034'},
   'janos': {'id': '035'},
   'jimenez': {'id': '036'},
   'juarez': {'id': '037'},
   'julimes': {'id': '038'},
   'lopez': {'id': '039'},
   'madera': {'id': '040'},
   'maguarichi': {'id': '041'},
   'manuel benavides': {'id': '042'},
   'matachi': {'id': '043'},
   'matamoros': {'id': '044'},
   'meoqui': {'id': '045'},
   'morelos': {'id': '046'},
   'moris': {'id': '047'},
   'namiquipa': {'id': '048'},
   'nonoava': {'id': '049'},
   'nuevo casas grandes': {'id': '050'},
   'ocampo': {'id': '051'},
   'ojinaga': {'id': '052'},
   'praxedis g. guerrero': {'id': '053'},
   'riva palacio': {'id': '054'},
   'rosales': {'id': '055'},
   'rosario': {'id': '056'},
   'san francisco de borja': {'id': '057'},
   'san francisco de conchos': {'id': '058'},
   'san francisco del oro': {'id': '059'},
   'santa barbara': {'id': '060'},
   'satevo': {'id': '061'},
   'saucillo': {'id': '062'},
   'temosachic': {'id': '063'},
   'el tule': {'id': '064'},
   'urique': {'id': '065'},
   'uruachi': {'id': '066'},
   'valle de zaragoza': {'id': '067'}}},
 'ciudad de mexico': {'id': '09',
  'municipios': {'azcapotzalco': {'id': '002'},
   'coyoacan': {'id': '003'},
   'cuajimalpa de morelos': {'id': '004'},
   'gustavo a. madero': {'id': '005'},
   'iztacalco': {'id': '006'},
   'iztapalapa': {'id': '007'},
   'la magdalena contreras': {'id': '008'},
   'milpa alta': {'id': '009'},
   'alvaro obregon': {'id': '010'},
   'tlahuac': {'id': '011'},
   'tlalpan': {'id': '012'},
   'xochimilco': {'id': '013'},
   'benito juarez': {'id': '014'},
   'cuauhtemoc': {'id': '015'},
   'miguel hidalgo': {'id': '016'},
   'venustiano carranza': {'id': '017'}}},
 'durango': {'id': '10',
  'municipios': {'canatlan': {'id': '001'},
   'canelas': {'id': '002'},
   'coneto de comonfort': {'id': '003'},
   'cuencame': {'id': '004'},
   'durango': {'id': '005'},
   'general simon bolivar': {'id': '006'},
   'gomez palacio': {'id': '007'},
   'guadalupe victoria': {'id': '008'},
   'guanacevi': {'id': '009'},
   'hidalgo': {'id': '010'},
   'inde': {'id': '011'},
   'lerdo': {'id': '012'},
   'mapimi': {'id': '013'},
   'mezquital': {'id': '014'},
   'nazas': {'id': '015'},
   'nombre de dios': {'id': '016'},
   'ocampo': {'id': '017'},
   'el oro': {'id': '018'},
   'otaez': {'id': '019'},
   'panuco de coronado': {'id': '020'},
   'penon blanco': {'id': '021'},
   'poanas': {'id': '022'},
   'pueblo nuevo': {'id': '023'},
   'rodeo': {'id': '024'},
   'san bernardo': {'id': '025'},
   'san dimas': {'id': '026'},
   'san juan de guadalupe': {'id': '027'},
   'san juan del rio': {'id': '028'},
   'san luis del cordero': {'id': '029'},
   'san pedro del gallo': {'id': '030'},
   'santa clara': {'id': '031'},
   'santiago papasquiaro': {'id': '032'},
   'suchil': {'id': '033'},
   'tamazula': {'id': '034'},
   'tepehuanes': {'id': '035'},
   'tlahualilo': {'id': '036'},
   'topia': {'id': '037'},
   'vicente guerrero': {'id': '038'},
   'nuevo ideal': {'id': '039'}}},
 'guanajuato': {'id': '11',
  'municipios': {'abasolo': {'id': '001'},
   'acambaro': {'id': '002'},
   'san miguel de allende': {'id': '003'},
   'apaseo el alto': {'id': '004'},
   'apaseo el grande': {'id': '005'},
   'atarjea': {'id': '006'},
   'celaya': {'id': '007'},
   'manuel doblado': {'id': '008'},
   'comonfort': {'id': '009'},
   'coroneo': {'id': '010'},
   'cortazar': {'id': '011'},
   'cueramaro': {'id': '012'},
   'doctor mora': {'id': '013'},
   'dolores hidalgo cuna de la independencia nacional': {'id': '014'},
   'guanajuato': {'id': '015'},
   'huanimaro': {'id': '016'},
   'irapuato': {'id': '017'},
   'jaral del progreso': {'id': '018'},
   'jerecuaro': {'id': '019'},
   'leon': {'id': '020'},
   'moroleon': {'id': '021'},
   'ocampo': {'id': '022'},
   'penjamo': {'id': '023'},
   'pueblo nuevo': {'id': '024'},
   'purisima del rincon': {'id': '025'},
   'romita': {'id': '026'},
   'salamanca': {'id': '027'},
   'salvatierra': {'id': '028'},
   'san diego de la union': {'id': '029'},
   'san felipe': {'id': '030'},
   'san francisco del rincon': {'id': '031'},
   'san jose iturbide': {'id': '032'},
   'san luis de la paz': {'id': '033'},
   'santa catarina': {'id': '034'},
   'santa cruz de juventino rosas': {'id': '035'},
   'santiago maravatio': {'id': '036'},
   'silao de la victoria': {'id': '037'},
   'tarandacuao': {'id': '038'},
   'tarimoro': {'id': '039'},
   'tierra blanca': {'id': '040'},
   'uriangato': {'id': '041'},
   'valle de santiago': {'id': '042'},
   'victoria': {'id': '043'},
   'villagran': {'id': '044'},
   'xichu': {'id': '045'},
   'yuriria': {'id': '046'}}},
 'guerrero': {'id': '12',
  'municipios': {'acapulco de juarez': {'id': '001'},
   'ahuacuotzingo': {'id': '002'},
   'ajuchitlan del progreso': {'id': '003'},
   'alcozauca de guerrero': {'id': '004'},
   'alpoyeca': {'id': '005'},
   'apaxtla': {'id': '006'},
   'arcelia': {'id': '007'},
   'atenango del rio': {'id': '008'},
   'atlamajalcingo del monte': {'id': '009'},
   'atlixtac': {'id': '010'},
   'atoyac de alvarez': {'id': '011'},
   'ayutla de los libres': {'id': '012'},
   'azoyu': {'id': '013'},
   'benito juarez': {'id': '014'},
   'buenavista de cuellar': {'id': '015'},
   'coahuayutla de jose maria izazaga': {'id': '016'},
   'cocula': {'id': '017'},
   'copala': {'id': '018'},
   'copalillo': {'id': '019'},
   'copanatoyac': {'id': '020'},
   'coyuca de benitez': {'id': '021'},
   'coyuca de catalan': {'id': '022'},
   'cuajinicuilapa': {'id': '023'},
   'cualac': {'id': '024'},
   'cuautepec': {'id': '025'},
   'cuetzala del progreso': {'id': '026'},
   'cutzamala de pinzon': {'id': '027'},
   'chilapa de alvarez': {'id': '028'},
   'chilpancingo de los bravo': {'id': '029'},
   'florencio villarreal': {'id': '030'},
   'general canuto a. neri': {'id': '031'},
   'general heliodoro castillo': {'id': '032'},
   'huamuxtitlan': {'id': '033'},
   'huitzuco de los figueroa': {'id': '034'},
   'iguala de la independencia': {'id': '035'},
   'igualapa': {'id': '036'},
   'ixcateopan de cuauhtemoc': {'id': '037'},
   'zihuatanejo de azueta': {'id': '038'},
   'juan r. escudero': {'id': '039'},
   'leonardo bravo': {'id': '040'},
   'malinaltepec': {'id': '041'},
   'martir de cuilapan': {'id': '042'},
   'metlatonoc': {'id': '043'},
   'mochitlan': {'id': '044'},
   'olinala': {'id': '045'},
   'ometepec': {'id': '046'},
   'pedro ascencio alquisiras': {'id': '047'},
   'petatlan': {'id': '048'},
   'pilcaya': {'id': '049'},
   'pungarabato': {'id': '050'},
   'quechultenango': {'id': '051'},
   'san luis acatlan': {'id': '052'},
   'san marcos': {'id': '053'},
   'san miguel totolapan': {'id': '054'},
   'taxco de alarcon': {'id': '055'},
   'tecoanapa': {'id': '056'},
   'tecpan de galeana': {'id': '057'},
   'teloloapan': {'id': '058'},
   'tepecoacuilco de trujano': {'id': '059'},
   'tetipac': {'id': '060'},
   'tixtla de guerrero': {'id': '061'},
   'tlacoachistlahuaca': {'id': '062'},
   'tlacoapa': {'id': '063'},
   'tlalchapa': {'id': '064'},
   'tlalixtaquilla de maldonado': {'id': '065'},
   'tlapa de comonfort': {'id': '066'},
   'tlapehuala': {'id': '067'},
   'la union de isidoro montes de oca': {'id': '068'},
   'xalpatlahuac': {'id': '069'},
   'xochihuehuetlan': {'id': '070'},
   'xochistlahuaca': {'id': '071'},
   'zapotitlan tablas': {'id': '072'},
   'zirandaro': {'id': '073'},
   'zitlala': {'id': '074'},
   'eduardo neri': {'id': '075'},
   'acatepec': {'id': '076'},
   'marquelia': {'id': '077'},
   'cochoapa el grande': {'id': '078'},
   'jose joaquin de herrera': {'id': '079'},
   'juchitan': {'id': '080'},
   'iliatenco': {'id': '081'},
   'las vigas': {'id': '082'},
   'nuu savi': {'id': '083'},
   'santa cruz del rincon': {'id': '084'},
   'san nicolas': {'id': '085'}}},
 'hidalgo': {'id': '13',
  'municipios': {'acatlan': {'id': '001'},
   'acaxochitlan': {'id': '002'},
   'actopan': {'id': '003'},
   'agua blanca de iturbide': {'id': '004'},
   'ajacuba': {'id': '005'},
   'alfajayucan': {'id': '006'},
   'almoloya': {'id': '007'},
   'apan': {'id': '008'},
   'el arenal': {'id': '009'},
   'atitalaquia': {'id': '010'},
   'atlapexco': {'id': '011'},
   'atotonilco el grande': {'id': '012'},
   'atotonilco de tula': {'id': '013'},
   'calnali': {'id': '014'},
   'cardonal': {'id': '015'},
   'cuautepec de hinojosa': {'id': '016'},
   'chapantongo': {'id': '017'},
   'chapulhuacan': {'id': '018'},
   'chilcuautla': {'id': '019'},
   'eloxochitlan': {'id': '020'},
   'emiliano zapata': {'id': '021'},
   'epazoyucan': {'id': '022'},
   'francisco i. madero': {'id': '023'},
   'huasca de ocampo': {'id': '024'},
   'huautla': {'id': '025'},
   'huazalingo': {'id': '026'},
   'huehuetla': {'id': '027'},
   'huejutla de reyes': {'id': '028'},
   'huichapan': {'id': '029'},
   'ixmiquilpan': {'id': '030'},
   'jacala de ledezma': {'id': '031'},
   'jaltocan': {'id': '032'},
   'juarez hidalgo': {'id': '033'},
   'lolotla': {'id': '034'},
   'metepec': {'id': '035'},
   'san agustin metzquititlan': {'id': '036'},
   'metztitlan': {'id': '037'},
   'mineral del chico': {'id': '038'},
   'mineral del monte': {'id': '039'},
   'la mision': {'id': '040'},
   'mixquiahuala de juarez': {'id': '041'},
   'molango de escamilla': {'id': '042'},
   'nicolas flores': {'id': '043'},
   'nopala de villagran': {'id': '044'},
   'omitlan de juarez': {'id': '045'},
   'san felipe orizatlan': {'id': '046'},
   'pacula': {'id': '047'},
   'pachuca de soto': {'id': '048'},
   'pisaflores': {'id': '049'},
   'progreso de obregon': {'id': '050'},
   'mineral de la reforma': {'id': '051'},
   'san agustin tlaxiaca': {'id': '052'},
   'san bartolo tutotepec': {'id': '053'},
   'san salvador': {'id': '054'},
   'santiago de anaya': {'id': '055'},
   'santiago tulantepec de lugo guerrero': {'id': '056'},
   'singuilucan': {'id': '057'},
   'tasquillo': {'id': '058'},
   'tecozautla': {'id': '059'},
   'tenango de doria': {'id': '060'},
   'tepeapulco': {'id': '061'},
   'tepehuacan de guerrero': {'id': '062'},
   'tepeji del rio de ocampo': {'id': '063'},
   'tepetitlan': {'id': '064'},
   'tetepango': {'id': '065'},
   'villa de tezontepec': {'id': '066'},
   'tezontepec de aldama': {'id': '067'},
   'tianguistengo': {'id': '068'},
   'tizayuca': {'id': '069'},
   'tlahuelilpan': {'id': '070'},
   'tlahuiltepa': {'id': '071'},
   'tlanalapa': {'id': '072'},
   'tlanchinol': {'id': '073'},
   'tlaxcoapan': {'id': '074'},
   'tolcayuca': {'id': '075'},
   'tula de allende': {'id': '076'},
   'tulancingo de bravo': {'id': '077'},
   'xochiatipan': {'id': '078'},
   'xochicoatlan': {'id': '079'},
   'yahualica': {'id': '080'},
   'zacualtipan de angeles': {'id': '081'},
   'zapotlan de juarez': {'id': '082'},
   'zempoala': {'id': '083'},
   'zimapan': {'id': '084'}}},
 'jalisco': {'id': '14',
  'municipios': {'acatic': {'id': '001'},
   'acatlan de juarez': {'id': '002'},
   'ahualulco de mercado': {'id': '003'},
   'amacueca': {'id': '004'},
   'amatitan': {'id': '005'},
   'ameca': {'id': '006'},
   'san juanito de escobedo': {'id': '007'},
   'arandas': {'id': '008'},
   'el arenal': {'id': '009'},
   'atemajac de brizuela': {'id': '010'},
   'atengo': {'id': '011'},
   'atenguillo': {'id': '012'},
   'atotonilco el alto': {'id': '013'},
   'atoyac': {'id': '014'},
   'autlan de navarro': {'id': '015'},
   'ayotlan': {'id': '016'},
   'ayutla': {'id': '017'},
   'la barca': {'id': '018'},
   'bolanos': {'id': '019'},
   'cabo corrientes': {'id': '020'},
   'casimiro castillo': {'id': '021'},
   'cihuatlan': {'id': '022'},
   'zapotlan el grande': {'id': '023'},
   'cocula': {'id': '024'},
   'colotlan': {'id': '025'},
   'concepcion de buenos aires': {'id': '026'},

In [14]:
OUTPUT_JSON = GAS_DATA / Path("catalogo_municipios.json")
with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(catalogo, f, indent=2, ensure_ascii=False)